### PR TITLE
three seconds is better

### PR DESCRIPTION
**Pull request by eordunoicloud**
changed blink off and on to 3000 ms

### CODE REVIEW

**Comment by ordunoesteban** [comment]
I will examine your proposed changes and will let you know.

**Comment by eordunoicloud** [comment]
Waiting on your response

**Comment by ordunoesteban** [comment]
I see the advantages of slow blink, so I merged your changes.

**Comment by ordunoesteban** [comment]
I merged your changes.

**Comment by ordunoesteban** [comment]
hope is the final

**Comment by ordunoesteban** [comment]
need to click the close and comment

**Pull request closed without merging**
